version: '3.7'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=s@sfje+4ydz4ac%p^q$o9+7!lavg+u-kcf#r)&-9yre%ped5b
      - POSTGRES_DB=shortener
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
      - EMAIL_HOST_USER=brevislink.robot@gmail.com
      - EMAIL_HOST_PASSWORD=dapxcbimuyjuhyqt
      - DB_NAME=shortener
      - DB_USER=django
      - DB_PASSWORD=s@sfje+4ydz4ac%p^q$o9+7!lavg+u-kcf#r)&-9yre%ped5b
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  db_data:
