version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=s@sfje+4ydz4ac%p^q$o9+7!lavg+u-kcf#r)&-9yre%ped5b
      - POSTGRES_DB=shortener
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-s@sfje+4ydz4ac%p^q$o9+7!lavg+u-kcf#r)&-9yre%ped5b=
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - EMAIL_HOST_USER=brevislink.robot@gmail.com
      - EMAIL_HOST_PASSWORD=dapxcbimuyjuhyqt
      - DB_NAME=shortener
      - DB_USER=django
      - DB_PASSWORD=s@sfje+4ydz4ac%p^q$o9+7!lavg+u-kcf#r)&-9yre%ped5b
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - app

volumes:
  static_data:
  db_data:
