version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=(9g_65x**tzds^oyw+zf_(t!p112cop0k(b8c#tgxj%ok06sp
      - POSTGRES_DB=demo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-=(9g_65x**tzds^oyw+zf_(t!p112cop0k(b8c#tgxj%ok06sp
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - EMAIL_HOST_USER=grodnopythonclassdemo@gmail.com
      - EMAIL_HOST_PASSWORD=faqcY5-taqses-gofcib
      - DB_NAME=demo
      - DB_USER=django
      - DB_PASSWORD=(9g_65x**tzds^oyw+zf_(t!p112cop0k(b8c#tgxj%ok06sp
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - app

volumes:
  static_data:
  db_data: