# Generated by Django 4.0.4 on 2022-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_bio_remove_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeword', models.CharField(max_length=16)),
            ],
        ),
    ]
