# Generated by Django 3.2.9 on 2022-07-15 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('full_url', models.URLField(unique=True, verbose_name='Полная ссылка')),
                ('url_hash', models.URLField(unique=True, verbose_name='Короткая ссылка')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время перехода по ссылке')),
                ('clicked_host', models.TextField(verbose_name='Откуда перешли')),
                ('clicked_conf', models.TextField(verbose_name='Конфигурация устройства пользователя')),
                ('clicked_ip', models.TextField(verbose_name='IP-адрес')),
                ('urlentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.urlentry', verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name_plural': 'Переходы',
            },
        ),
    ]
