# Generated by Django 4.0.4 on 2022-05-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_leads_urlentry_urlentry_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='urlentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.urlentry'),
        ),
    ]
