# Generated by Django 3.2.9 on 2022-07-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20220713_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlentry',
            name='datetime_available_from',
        ),
        migrations.RemoveField(
            model_name='urlentry',
            name='datetime_available_to',
        ),
        migrations.RemoveField(
            model_name='urlentry',
            name='partner_ads',
        ),
    ]
