# Generated by Django 3.2.9 on 2022-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_remove_urlentry_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='url_text',
            field=models.TextField(verbose_name='Текст ссылки'),
        ),
    ]
