# Generated by Django 3.2.9 on 2022-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_alter_urlentry_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='url_text',
            field=models.TextField(verbose_name='Полная ссылка'),
        ),
    ]
