# Generated by Django 3.2.9 on 2022-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0012_auto_20220714_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
