# Generated by Django 3.2.9 on 2022-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0013_alter_urlentry_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='follow_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время перехода по ссылке'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='follower_fromwhere',
            field=models.TextField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='follower_info',
            field=models.TextField(verbose_name='Откуда перешли'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='follower_os_info',
            field=models.TextField(verbose_name='Конфигурация устройства пользователя'),
        ),
    ]
