# Generated by Django 3.2.9 on 2022-07-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0016_rename_url_short_urlentry_url_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlentry',
            old_name='author',
            new_name='owner',
        ),
    ]
