# Generated by Django 3.2.9 on 2022-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0017_rename_author_urlentry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
