# Generated by Django 3.2.9 on 2022-07-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0018_alter_urlentry_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlentry',
            old_name='create_date',
            new_name='created_at',
        ),
    ]
