# Generated by Django 3.2.9 on 2022-07-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0020_rename_follow_date_leads_clicked_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='follower_info',
            new_name='clicked_host',
        ),
    ]
