# Generated by Django 3.2.9 on 2022-07-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0021_rename_follower_info_leads_clicked_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='follower_os_info',
            new_name='clicked_conf',
        ),
    ]
