# Generated by Django 3.2.9 on 2022-07-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0022_rename_follower_os_info_leads_clicked_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='follower_fromwhere',
            new_name='clicked_ip',
        ),
    ]
