# Generated by Django 3.2.9 on 2022-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0023_rename_follower_fromwhere_leads_clicked_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время перехода по ссылке'),
        ),
    ]
