# Generated by Django 3.2.9 on 2022-07-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0025_alter_urlentry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='urlentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.urlentry', verbose_name='Короткая ссылка'),
        ),
    ]
