# Generated by Django 3.2.9 on 2022-07-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0026_alter_leads_urlentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Переходы'},
        ),
    ]
