# Generated by Django 3.2.9 on 2022-07-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0027_alter_leads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlentry',
            options={'verbose_name_plural': 'Ссылки'},
        ),
    ]
